"""Core data models for Aether BTC.

All P&L calculations are NET of costs (commissions, slippage, funding costs).
Adapted from Aether v3 with crypto-specific leverage/liquidation/funding fields.
"""

from dataclasses import dataclass, field
from datetime import datetime, timedelta
from typing import Any

from aether_btc.core.enums import (
    ExitReason,
    OrderIntent,
    OrderStatus,
    OrderType,
    PositionSide,
    SignalState,
    SignalType,
)

_DEFAULT_SIGNAL_TTL = timedelta(hours=4)  # Shorter TTL for 15min crypto

# Binance Futures maintenance margin rate (BTC/USDT, bracket 1)
MAINTENANCE_MARGIN_RATE = 0.004


@dataclass
class Signal:
    """A trading signal generated by the GA-evolved scoring function."""

    pair: str
    signal_type: SignalType
    confidence: float
    timestamp: datetime
    metadata: dict[str, Any] = field(default_factory=dict)
    expiry: datetime | None = None
    state: SignalState = SignalState.GENERATED

    def __post_init__(self) -> None:
        if not 0 <= self.confidence <= 1:
            raise ValueError(f"Confidence must be between 0 and 1, got {self.confidence}")
        if self.expiry is None:
            self.expiry = self.timestamp + _DEFAULT_SIGNAL_TTL

    @property
    def is_expired(self) -> bool:
        if self.expiry is None:
            return False
        return datetime.now() > self.expiry

    def to_dict(self) -> dict[str, Any]:
        return {
            "pair": self.pair,
            "signal_type": self.signal_type.value,
            "confidence": self.confidence,
            "timestamp": self.timestamp.isoformat(),
            "metadata": self.metadata,
            "expiry": self.expiry.isoformat() if self.expiry else None,
            "state": self.state.value,
        }


@dataclass
class Order:
    """A trade order. Generated on bar T, queued for execution at bar T+1 OPEN."""

    pair: str
    intent: OrderIntent
    quantity: float  # BTC quantity (fractional)
    order_type: OrderType = OrderType.MARKET
    limit_price: float | None = None
    stop_loss: float | None = None
    take_profit: float | None = None
    leverage: float = 1.0
    confidence: float = 0.0
    generated_at: datetime = field(default_factory=datetime.now)
    status: OrderStatus = OrderStatus.PENDING
    metadata: dict[str, Any] = field(default_factory=dict)


@dataclass
class Position:
    """An open leveraged position with funding cost tracking.

    Key crypto adaptations from Aether v3:
    - leverage field (1.0-20.0)
    - liquidation_price calculated from leverage
    - funding_cost_accrued replaces borrow_cost_accrued
    - quantity is float (fractional BTC)
    """

    pair: str
    quantity: float
    entry_price: float
    side: PositionSide = PositionSide.LONG
    leverage: float = 1.0
    stop_loss: float | None = None
    take_profit: float | None = None
    current_price: float | None = None
    opened_at: datetime = field(default_factory=datetime.now)
    entry_commission: float = 0.0
    funding_cost_accrued: float = 0.0
    metadata: dict[str, Any] = field(default_factory=dict)

    @property
    def margin_used(self) -> float:
        """Margin (collateral) locked for this position."""
        return self.quantity * self.entry_price / self.leverage

    @property
    def notional_value(self) -> float:
        """Full notional value of the position."""
        return self.quantity * self.entry_price

    @property
    def current_notional(self) -> float:
        """Current notional value based on current price."""
        price = self.current_price or self.entry_price
        return self.quantity * price

    @property
    def liquidation_price(self) -> float:
        """Liquidation price based on leverage and maintenance margin.

        Long: entry * (1 - 1/leverage + maintenance_margin)
        Short: entry * (1 + 1/leverage - maintenance_margin)
        """
        mm = MAINTENANCE_MARGIN_RATE
        if self.side == PositionSide.LONG:
            return self.entry_price * (1 - 1 / self.leverage + mm)
        return self.entry_price * (1 + 1 / self.leverage - mm)

    @property
    def gross_unrealized_pnl(self) -> float:
        """Unrealized P&L before costs, accounting for leverage."""
        if self.current_price is None:
            return 0.0
        price_change_pct = (self.current_price - self.entry_price) / self.entry_price
        if self.side == PositionSide.SHORT:
            price_change_pct = -price_change_pct
        return price_change_pct * self.leverage * self.margin_used

    @property
    def net_unrealized_pnl(self) -> float:
        """Unrealized P&L NET of all costs."""
        return self.gross_unrealized_pnl - self.entry_commission - self.funding_cost_accrued

    @property
    def unrealized_pnl_percent(self) -> float:
        """NET unrealized P&L as percentage of margin used."""
        if self.margin_used == 0:
            return 0.0
        return (self.net_unrealized_pnl / self.margin_used) * 100

    def should_stop_loss(self, price: float | None = None) -> bool:
        check_price = price or self.current_price
        if self.stop_loss is None or check_price is None:
            return False
        if self.side == PositionSide.LONG:
            return check_price <= self.stop_loss
        return check_price >= self.stop_loss

    def should_take_profit(self, price: float | None = None) -> bool:
        check_price = price or self.current_price
        if self.take_profit is None or check_price is None:
            return False
        if self.side == PositionSide.LONG:
            return check_price >= self.take_profit
        return check_price <= self.take_profit

    def is_liquidated(self, price: float | None = None) -> bool:
        """Check if position would be liquidated at given price."""
        check_price = price or self.current_price
        if check_price is None:
            return False
        if self.side == PositionSide.LONG:
            return check_price <= self.liquidation_price
        return check_price >= self.liquidation_price

    def accrue_funding_cost(self, funding_rate: float) -> float:
        """Accrue funding cost. Positive rate: longs pay, shorts receive.

        Returns cost accrued (positive = paid, negative = received).
        """
        cost = self.notional_value * funding_rate
        if self.side == PositionSide.SHORT:
            cost = -cost  # Shorts receive when rate is positive
        self.funding_cost_accrued += cost
        return cost

    def update_price(self, price: float) -> None:
        self.current_price = price

    def to_dict(self) -> dict[str, Any]:
        return {
            "pair": self.pair,
            "quantity": self.quantity,
            "entry_price": self.entry_price,
            "side": self.side.value,
            "leverage": self.leverage,
            "margin_used": self.margin_used,
            "notional_value": self.notional_value,
            "liquidation_price": self.liquidation_price,
            "stop_loss": self.stop_loss,
            "take_profit": self.take_profit,
            "current_price": self.current_price,
            "net_unrealized_pnl": self.net_unrealized_pnl,
            "funding_cost_accrued": self.funding_cost_accrued,
            "opened_at": self.opened_at.isoformat(),
        }


@dataclass
class Trade:
    """An executed trade record."""

    pair: str
    intent: OrderIntent
    quantity: float
    price: float
    commission: float
    slippage: float
    leverage: float
    executed_at: datetime

    @property
    def notional_value(self) -> float:
        return self.price * self.quantity


@dataclass
class ClosedPosition:
    """A closed position with full cost breakdown.

    All P&L is NET. Adapted from Aether v3 with funding_cost replacing borrow_cost.
    """

    pair: str
    quantity: float
    entry_price: float
    exit_price: float
    side: PositionSide
    leverage: float
    opened_at: datetime
    closed_at: datetime
    exit_reason: ExitReason
    entry_commission: float = 0.0
    exit_commission: float = 0.0
    entry_slippage: float = 0.0
    exit_slippage: float = 0.0
    funding_cost: float = 0.0

    @property
    def margin_used(self) -> float:
        return self.quantity * self.entry_price / self.leverage

    @property
    def gross_pnl(self) -> float:
        """Gross P&L accounting for leverage."""
        price_change_pct = (self.exit_price - self.entry_price) / self.entry_price
        if self.side == PositionSide.SHORT:
            price_change_pct = -price_change_pct
        return price_change_pct * self.leverage * self.margin_used

    @property
    def total_costs(self) -> float:
        return (
            self.entry_commission
            + self.exit_commission
            + self.entry_slippage
            + self.exit_slippage
            + self.funding_cost
        )

    @property
    def net_pnl(self) -> float:
        """NET P&L after all costs."""
        return self.gross_pnl - self.total_costs

    @property
    def net_pnl_percent(self) -> float:
        """NET P&L as percentage of margin used."""
        if self.margin_used == 0:
            return 0.0
        return (self.net_pnl / self.margin_used) * 100

    @property
    def cost_drag_percent(self) -> float:
        if self.margin_used == 0:
            return 0.0
        return (self.total_costs / self.margin_used) * 100

    @property
    def hold_duration_hours(self) -> float:
        delta = self.closed_at - self.opened_at
        return delta.total_seconds() / 3600

    @property
    def leverage_used(self) -> float:
        return self.leverage


@dataclass
class EquitySnapshot:
    """Periodic equity snapshot for equity curve tracking."""

    timestamp: datetime
    cash: float
    margin_in_use: float
    unrealized_pnl: float
    total_equity: float
    leverage_ratio: float
    bar_return: float = 0.0
